#good example of nested escaped xargs nested bash etc #nested #escaping nested #complicated
shopt -s globstar
shroot=/sh
afile="$shroot"/b2323_generated_functions.sh
echo '#generated by '$shroot'/mkf.sh' | . /sh/writeasroot.sh $afile
echo 'generating: ' | . /sh/appendasroot.sh $afile
ls /sh | grep -E '\.sh$' |xargs -i bash -c '
  base=$(echo $(basename {})|grep -o '\''^[^.]*'\''); 
  echo function $base\(\) \{ . \"/sh/$base.sh\" \"\$\@\"\; \} >> '$afile

. $afile

	#echo 'alias mkalias="echo aliases present"' >> $afile #I am so clever - prevent unneeded invocations of this
