bvar 4t /media/b/4t
bvar mnyamtrgx '\$([0-9]{1,}\.[0-9]{2})($|[^0-9])'
bvar q "'"
bvar qq '"'
bvar oosp acct_tax_outofstatepurchase
bvar bank 'bankaccttran'
bvar zero $'\0'
bvar aud '\.(wav|WAV|ogg|mp3|MP3)$'
bvar lau hygiene:laundry
bvar tax acct:taxprep
bvar work work:pc:custom:acct:taxable
bvar farm work:farm:acct:taxable:W-2
bvar tom $work:tomato:harvest
bvar down ~/Downloads
bvar gs '--------------------------------------------------------------------------------'
bvar fence cabbage:pestcontrol:repair:electricfence
bvar textdoc '.*(docx?|wps|rtf|txt|odt)$'
bvar unsafe '/tmp|backup|archive|nocopy|copy_|_copy|Greed[1-9]|Moth[1-9]|\.img(.gz)?'
bvar regexb '(^|/)b[0-9]*_'
bvar bregex '(^|/)b[0-9]*_'
bvar acctregex 'ty(20)?[12][0-9]|acct|tax|income|expense|W-2|1099-'
bvar eregex 'headl|cam|power|AC|DC|AAA?|batter|meter|router|extender|printer|scanner|camera|webcam|ethernet|alarm|watch|computer|laptop|desktop|monitor|electric|tester|mouse|keyboard|wireless|remote'
bvar flu 'fl(ou|uo)r[oi]'
bvar imgfilrgx '\.(JPE?G|jpe?g|GIF|gif|TIFF?|tiff?|PNG|png|BMP|bmp)$'
bvar leaf '[^/]*/?$'
bvar bleaf $regexb$leaf
bvar black 'file_box_black_holes'
bvar workwear 'work|safety|goggle|helmet'
bvar propac 'propac product packaging Greed3'
