#good example of nested escaped xargs nested bash etc #nested #escaping nested #complicated
shopt -s globstar
shroot=/sh
afile="$shroot"/b2323_generated_functions.sh
echo '#generated by '$shroot'/mkf.sh' > $afile
echo 'generating: ' $afile
line1='base=$(echo -n {}|grep -o "^[^.]*"); echo "$base"; 
      echo "function $base() { if test -e /sh/$base.sh; then sfile=/sh/$base.sh; else sfile=/sh_loc/$base.sh; fi; . "$sfile; }'
#line1='base=$(echo $(basename {})|grep -o "^[^.]*"); '
#line2='echo function "$base"() { test -e /sh/$base.sh && . /sh/$base.sh "$@"; } >> '$afile
ls /sh | grep -E '\.sh$' |xargs -i bash -c "$line1"
#. $afile
#cp -a "$afile" "$(b 644)"


##########echo 'alias mkalias="echo aliases present"' >> $afile #I am so clever - prevent unneeded invocations of this
