#good example of nested escaped xargs nested bash etc #nested #escaping nested #complicated
shopt -s globstar
shroot=/sh
test -d $(b 1) && cp $(b 1)/*sh /sh  #master scripts should be kept in b1_ directory on sd card and copied to /sh
afile="$shroot"/b2323_generated_functions.sh
echo '#generated by '$shroot'/mkf.sh' > $afile
echo 'generating: ' $afile
find "$shroot"| grep -E '\.sh$' |xargs -i bash -c 'base=$(echo $(basename {})|grep -o '\''^[^.]*'\''); echo function $base\(\) \{ . \"{}\" \"\$\@\"\; \} >> '$afile
#echo 'alias mkalias="echo aliases present"' >> $afile #I am so clever - prevent unneeded invocations of this
. $afile
