#good example of nested escaped xargs nested bash etc #nested #escaping nested #complicated
shopt -s globstar
#shroot=$(readlink -e /b/l/1)
shroot=/b/l/1
afile="$shroot"/generated_functions.sh
echo '#generated by '$shroot'/mkf.sh' > $afile
find "$shroot"/*.sh |xargs -i 'base=$(echo $(basename {})|grep -o '\''^[^.]*'\''); echo function $base\(\) \{ . \"{}\" \"\$\@\"\; \} >> '$afile
#echo 'alias mkalias="echo aliases present"' >> $afile #I am so clever - prevent unneeded invocations of this
. $afile
